CREATE TABLE IF NOT EXISTS internal_user
(
    id         INTEGER GENERATED ALWAYS AS IDENTITY,
    user_id    INT4 NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);
