CREATE TABLE IF NOT EXISTS admin_user
(
    id         INTEGER GENERATED ALWAYS AS IDENTITY,
    tenant_id  uuid NOT NULL REFERENCES tenant (id) ON DELETE CASCADE,
    user_id    INT4 NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);
